FROM alpine:3

LABEL author="Muhamad Yasir Noval"
LABEL company="IYY Family" website="https://www.iyyfamilyrevtech.com"

RUN mkdir hello
RUN echo "Hello World" > "hello/world.txt"
RUN cat "hello/world.txt"

CMD cat "hello/world.txt"